force-app/main/default/objects/Account/fields/IdentificacaoFiscal__c.field-meta.xml
<CustomField>
    <fullName>IdentificacaoFiscal__c</fullName>
    <label>Identificação Fiscal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IdentificacaoFiscalSemFormatacao__c.field-meta.xml
<CustomField>
    <fullName>IdentificacaoFiscalSemFormatacao__c</fullName>
    <formula>SUBSTITUTE( SUBSTITUTE( SUBSTITUTE( IdentificacaoFiscal__c, &apos;.&apos;,&apos;&apos; ), &apos;-&apos;,&apos;&apos; ),&apos;/&apos;,&apos;&apos; )</formula>
    <label>Identificação Fiscal sem formatação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/TipoIdentificacaoFiscal__c.field-meta.xml
<CustomField>
    <fullName>TipoIdentificacaoFiscal__c</fullName>
    <label>Tipo de Identificação Fiscal</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CNPJ</fullName>
            </value>
            <value>
                <fullName>CPF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountDAO.cls
public with sharing class AccountDAO {
    
    public static Account getAccountsById(Id accountId){
        List<Account> accountList = getAccountsById(new Set<Id>{accountId});
        if(accountList.size() == 0){
            return null;
        }
        return accountList.get(0);
    }

    public static List<Account> getAccountsById(Set<Id> accountIds){
        return [SELECT
                    Id,
                    Name,
                    identificacaoFiscal__c,
                    tipoIdentificacaoFiscal__c,
                    IdentificacaoFiscalSemFormatacao__c
                FROM
                    Account
                WHERE
                    Id IN: accountIds];
    }

    public static List<Account> getAccountsWithIdentifier(Set<String> setIdentificacao){
        return [SELECT
                    Id,
                    Name,
                    identificacaoFiscal__c,
                    tipoIdentificacaoFiscal__c,
                    IdentificacaoFiscalSemFormatacao__c
                FROM
                    Account
                WHERE
                    identificacaoFiscal__c IN : setIdentificacao];
    }

    public static List<Account> getParentAccounts(Set<String> raizCnpj){
        return [SELECT
                    Id,
                    Name,
                    identificacaoFiscal__c,
                    tipoIdentificacaoFiscal__c,
                    IdentificacaoFiscalSemFormatacao__c 
                FROM
                    Account
                WHERE
                    identificacaoFiscal__c LIKE '%0001%'
                    AND tipoIdentificacaoFiscal__c = 'CNPJ'
                    AND IdentificacaoFiscalSemFormatacao__c LIKE : raizCnpj];
    }

    public static List<Account> getSubsidiaryAccounts(Set<String> raizCnpjMatrizes){
        return [SELECT
                    Id,
                    Name,
                    identificacaoFiscal__c,
                    tipoIdentificacaoFiscal__c,
                    IdentificacaoFiscalSemFormatacao__c 
                FROM
                    Account
                WHERE
                    (NOT identificacaoFiscal__c LIKE : '%0001%')
                    AND IdentificacaoFiscalSemFormatacao__c LIKE : raizCnpjMatrizes];
    }
}