force-app/main/default/objects/Endereco__c/Endereco__c.object-meta.xml
<CustomObject>
    <label>Endereço</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>Endereço Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Endereco__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>EnderecosConta</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Endereco__c/fields/Geolocalizacao__c.field-meta.xml
<CustomField>
    <fullName>Geolocalizacao__c</fullName>
    <label>Geolocalização</label>
    <scale>10</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Endereco__c/fields/Municipio__c.field-meta.xml
<CustomField>
    <fullName>Municipio__c</fullName>
    <label>Município</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Endereco__c/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Endereco__c/fields/Pais__c.field-meta.xml
<CustomField>
    <fullName>Pais__c</fullName>
    <label>País</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Brasil</fullName>
                <default>true</default>
                <label>Brasil</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Endereco__c/fields/TipoEndereco__c.field-meta.xml
<CustomField>
    <fullName>TipoEndereco__c</fullName>
    <label>Tipo de Endereço</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente</fullName>
            </value>
            <value>
                <fullName>Cobrança</fullName>
            </value>
            <value>
                <fullName>Entrega</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnderecoDAO.cls
public with sharing class EnderecoDAO {
    
    public static Endereco__c getEnderecoPorId(Id enderecoId){
        List<Endereco__c> enderecos = getEnderecoPorId(new Set<Id>{enderecoId});
        if(enderecos.size() == 0){
            return null;
        }
        return enderecos.get(0);
    }

    public static List<Endereco__c> getEnderecoPorId(Set<Id> enderecoIds){
        return [SELECT
                    Id,
                    Name,
                    Ativo__c,
                    Account__c,
                    Bairro__c,
                    CEP__c,
                    Complemento__c,
                    Estado__c,
                    EnderecoCompleto__c,
                    Geolocalizacao__c,
                    Logradouro__c,
                    Municipio__c,
                    Numero__c,
                    Pais__c,
                    TipoEndereco__c
                FROM
                    Endereco__c
                WHERE
                    Id IN: enderecoIds];
    }
}